package com.neobe.bto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Negativa")
public class Negativa implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    
	@javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "NEGATIVA_ID_GENERATOR")
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(sequenceName = "NEGATIVA_ID_SEQ", name = "NEGATIVA_ID_GENERATOR")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label(value = "Código da negativa")
	private java.lang.String codigo;

	@org.kie.api.definition.type.Label(value = "Descrição da negativa")
	private java.lang.String descricao;

	public Negativa() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(java.lang.String codigo) {
		this.codigo = codigo;
	}

	public java.lang.String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(java.lang.String descricao) {
		this.descricao = descricao;
	}

	public Negativa(java.lang.Long id, java.lang.String codigo,
			java.lang.String descricao) {
		this.id = id;
		this.codigo = codigo;
		this.descricao = descricao;
	}

}