package com.neobe.bto;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "Solicitante")
public class Solicitante implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Identificador do solicitante")
	@javax.persistence.Id
	private java.lang.Long id;
	@org.kie.api.definition.type.Label("Razão social do solicitante")
	private java.lang.String razaoSocial;
	@org.kie.api.definition.type.Label("Solicitante afastado na data de solicitação")
	private java.lang.Boolean afastado;

	@org.kie.api.definition.type.Label("Solicitante bloqueado na data de solicitação")
	private java.lang.Boolean bloqueado;

	public Solicitante() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getRazaoSocial() {
		return this.razaoSocial;
	}

	public void setRazaoSocial(java.lang.String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	public java.lang.Boolean getAfastado() {
		return this.afastado;
	}

	public void setAfastado(java.lang.Boolean afastado) {
		this.afastado = afastado;
	}

	public java.lang.Boolean getBloqueado() {
		return this.bloqueado;
	}

	public void setBloqueado(java.lang.Boolean bloqueado) {
		this.bloqueado = bloqueado;
	}

	public Solicitante(java.lang.Long id, java.lang.String razaoSocial,
			java.lang.Boolean afastado, java.lang.Boolean bloqueado) {
		this.id = id;
		this.razaoSocial = razaoSocial;
		this.afastado = afastado;
		this.bloqueado = bloqueado;
	}

}